In [1]:
import pandas as pd

In [2]:
#lo primero que voy a hacer es analizar las bases de datos, voy a mirar como de grandes son y si es necesario limpiarlas.
#Es decir, si tienen valores NULL, mirar si hay que cambiarlos o si es necesario, dejarlo como esta.

In [3]:
df = pd.read_csv("data/claustro.csv",sep=";")

In [4]:
df

               Nombre Rol Vertical   Promocion    Campus
0           Noa Yáñez  TA       DS  Septiembre    Madrid
1   Saturnina Benitez  TA       DS  Septiembre    Madrid
2          Anna Feliu  TA       FS  Septiembre    Madrid
3       Rosalva Ayuso  TA       FS  Septiembre  Valencia
4    Ana Sofía Ferrer  TA       FS     Febrero  Valencia
5     Angélica Corral  TA       FS     Febrero    Madrid
6         Ariel Lledó  TA       DS  Septiembre    Madrid
7         Mario Prats  LI       FS     Febrero  Valencia
8   Luis Ángel Suárez  LI       FS  Septiembre    Madrid
9  María Dolores Diaz  LI       DS  Septiembre    Madrid

In [5]:
#Parece estar bien, podemos continuar.

In [6]:
df_ds1 = pd.read_csv("data/listado_DS_clase_1.csv",sep=";")

In [7]:
df_ds1

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment
0,Jafet Casals,Jafet_Casals@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
1,Jorge Manzanares,Jorge_Manzanares@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
2,Onofre Adadia,Onofre_Adadia@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,No Apto,Apto
3,Merche Prada,Merche_Prada@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,No Apto,Apto,No Apto
4,Pilar Abella,Pilar_Abella@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
5,Leoncio Tena,Leoncio_Tena@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
6,Odalys Torrijos,Odalys_Torrijos@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
7,Eduardo Caparrós,Eduardo_Caparrós@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
8,Ignacio Goicoechea,Ignacio_Goicoechea@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,No Apto,Apto
9,Clementina Santos,Clementina_Santos@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
10,Daniela Falcó,Daniela_Falcó@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
11,Abraham Vélez,Abraham_Vélez@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,No Apto,Apto,Apto
12,Maximiliano Menéndez,Maximiliano_Menéndez@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
13,Anita Heredia,Anita_Heredia@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
14,Eli Casas,Eli_Casas@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto

In [8]:
df_ds2 = pd.read_csv("data/listado_DS_clase_2.csv",sep=";")

In [9]:
df_ds2

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment
0,Guillermo Borrego,Guillermo_Borrego@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,No Apto,Apto,No Apto
1,Sergio Aguirre,Sergio_Aguirre@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,Apto,Apto,No Apto
2,Carlito Carrión,Carlito_Carrión@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,Apto,Apto,Apto
3,Haydée Figueroa,Haydée_Figueroa@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,Apto,Apto,Apto
4,Chita Mancebo,Chita_Mancebo@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,Apto,Apto
5,Joaquina Asensio,Joaquina_Asensio@gmail.com,Febrero,12/02/2024,Madrid,No Apto,No Apto,Apto,Apto,Apto
6,Cristian Sarabia,Cristian_Sarabia@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,No Apto,Apto,Apto
7,Isabel Ibáñez,Isabel_Ibáñez@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,Apto,Apto
8,Desiderio Jordá,Desiderio_Jordá@gmail.com,Febrero,12/02/2024,Madrid,No Apto,Apto,No Apto,No Apto,Apto
9,Rosalina Llanos,Rosalina_Llanos@gmail.com,Febrero,12/02/2024,Madrid,Apto,Apto,Apto,Apto,Apto

In [10]:
df_fs1 = pd.read_csv("data/listado_FS_clase_1.csv",sep=";")

In [11]:
# al tener mal escrito Fullstack en el csv lo cambiamos para darle solidez al atributo

df_fs1.rename(columns={'Proyecto_FullSatck': 'Proyecto_FullStack'}, inplace=True)

In [12]:
df_fs1

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_Backend,Proyecto_React,Proyecto_FullStack
0,Amor Larrañaga,Amor_Larrañaga@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,No Apto
1,Teodoro Alberola,Teodoro_Alberola@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,No Apto,Apto,No Apto,Apto
2,Cleto Plana,Cleto_Plana@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,No Apto,Apto
3,Aitana Sebastián,Aitana_Sebastián@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,No Apto,Apto
4,Dolores Valbuena,Dolores_Valbuena@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,No Apto
5,Julie Ferrer,Julie_Ferrer@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,No Apto,No Apto,Apto,No Apto
6,Mireia Cabañas,Mireia_Cabañas@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
7,Flavia Amador,Flavia_Amador@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,No Apto,Apto,Apto
8,Albino Macias,Albino_Macias@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
9,Ester Sánchez,Ester_Sánchez@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,No Apto,Apto
10,Luis Miguel Galvez,Luis_Miguel_Galvez@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,Apto,Apto,Apto,Apto
11,Loida Arellano,Loida_Arellano@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto
12,Heraclio Duque,Heraclio_Duque@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,No Apto,No Apto,No Apto
13,Herberto Figueras,Herberto_Figueras@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,Apto

In [13]:
df_fs2 = pd.read_csv("data/listado_FS_clase_2.csv",sep=";")

In [14]:
# al tener mal escrito Fullstack en el csv lo cambiamos para darle solidez al atributo

df_fs2.rename(columns={'Proyecto_FullSatck': 'Proyecto_FullStack'}, inplace=True)

In [15]:
df_fs2

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_Backend,Proyecto_React,Proyecto_FullStack
0,Teresa Laguna,Teresa_Laguna@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
1,Estrella Murillo,Estrella_Murillo@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,Apto,Apto
2,Ernesto Uriarte,Ernesto_Uriarte@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
3,Daniela Guitart,Daniela_Guitart@gmail.com,Febrero,12/02/2024,Valencia,Apto,No Apto,No Apto,Apto,Apto
4,Timoteo Trillo,Timoteo_Trillo@gmail.com,Febrero,12/02/2024,Valencia,No Apto,Apto,Apto,Apto,No Apto
5,Ricarda Tovar,Ricarda_Tovar@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto
6,Alejandra Vilaplana,Alejandra_Vilaplana@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,No Apto,Apto,Apto
7,Daniel Rosselló,Daniel_Rosselló@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,Apto,No Apto,No Apto
8,Rita Olivares,Rita_Olivares@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,No Apto,Apto,Apto
9,Cleto Montes,Cleto_Montes@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,Apto,Apto
10,Marino Castilla,Marino_Castilla@gmail.com,Febrero,12/02/2024,Valencia,No Apto,No Apto,Apto,No Apto,No Apto
11,Estefanía Valcárcel,Estefanía_Valcárcel@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,No Apto,Apto
12,Noemí Vilanova,Noemí_Vilanova@gmail.com,Febrero,12/02/2024,Valencia,Apto,No Apto,No Apto,Apto,Apto

In [16]:
#La tilde de promoción dara problemas mas adelante, lo quitamos.

df_ds1.rename(columns={'Promoción': 'Promocion'}, inplace=True)
df_ds2.rename(columns={'Promoción': 'Promocion'}, inplace=True)
df_fs1.rename(columns={'Promoción': 'Promocion'}, inplace=True)
df_fs2.rename(columns={'Promoción': 'Promocion'}, inplace=True)

In [17]:
#aqui añado el index como columna y de paso le cambio el nombre
df = df.reset_index()
df.rename(columns={'index': 'Docente_id'}, inplace=True)
#Hacemos mas cambios para adaptarlo a nuestra DB.
df.rename(columns={'Vertical': 'Vertical_id'}, inplace=True)

In [18]:
#cambiamos el Vertical_ID segun correponda a el campus y a la vertical.
df.loc[(df['Promocion'] == 'Septiembre') & (df["Vertical_id"] == "DS"), 'Vertical_id'] = 'DS_SEP'
df.loc[(df['Promocion'] == 'Septiembre') & (df["Vertical_id"] == "FS"), 'Vertical_id'] = 'FS_SEP'
df.loc[(df['Promocion'] == 'Febrero') & (df["Vertical_id"] == "FS"), 'Vertical_id'] = 'FS_FEB'
df

   Docente_id              Nombre Rol Vertical_id   Promocion    Campus
0           0           Noa Yáñez  TA      DS_SEP  Septiembre    Madrid
1           1   Saturnina Benitez  TA      DS_SEP  Septiembre    Madrid
2           2          Anna Feliu  TA      FS_SEP  Septiembre    Madrid
3           3       Rosalva Ayuso  TA      FS_SEP  Septiembre  Valencia
4           4    Ana Sofía Ferrer  TA      FS_FEB     Febrero  Valencia
5           5     Angélica Corral  TA      FS_FEB     Febrero    Madrid
6           6         Ariel Lledó  TA      DS_SEP  Septiembre    Madrid
7           7         Mario Prats  LI      FS_FEB     Febrero  Valencia
8           8   Luis Ángel Suárez  LI      FS_SEP  Septiembre    Madrid
9           9  María Dolores Diaz  LI      DS_SEP  Septiembre    Madrid

In [19]:
#las columnas de promocion y Campus se utilizaran en otra Dataframe, las guardamos en otra variable.

Campus = df["Campus"]
Promocion = df["Promocion"]

In [20]:
#Campus no lo vamos a necesitar, lo quitamos.
df = df.drop("Campus", axis=1)
df = df.drop("Promocion", axis=1)
df

   Docente_id              Nombre Rol Vertical_id
0           0           Noa Yáñez  TA      DS_SEP
1           1   Saturnina Benitez  TA      DS_SEP
2           2          Anna Feliu  TA      FS_SEP
3           3       Rosalva Ayuso  TA      FS_SEP
4           4    Ana Sofía Ferrer  TA      FS_FEB
5           5     Angélica Corral  TA      FS_FEB
6           6         Ariel Lledó  TA      DS_SEP
7           7         Mario Prats  LI      FS_FEB
8           8   Luis Ángel Suárez  LI      FS_SEP
9           9  María Dolores Diaz  LI      DS_SEP

In [21]:
#Con la dataframe lista, lo guardamos.
ruta = 'data_limpiado/cuerpo_docente.csv'
df.to_csv(ruta, index=False)

TUTORIAL METER CSV CREADO A POSTGRE SQL




primero creamos la tabla en postgre SQL.

CREATE TABLE cuerpo_docente (
    Docente_id SERIAL PRIMARY KEY,
    nombre TEXT,
    rol TEXT,
    vertical_ID TEXT
    FOREIGN KEY (vertical_ID) REFERENCES vertical(Vertical_id)
);

VAMOS A TOOLS -> QUERY TOOLS

pega el comando de arriba.

Si sale bien, haz click derecho en Tables -> refresh para que aparezca.
Si quieres comprobar las tablas, dale click derecho -> properties -> columns

entramos a la consola de postgresql (tools -> PSQL tool)

\copy cuerpo_docente from 'C:\Users\Usuario\Desktop\2309_sql_thebridge\Practica\4-Proyecto\data_limpiado\cuerpo_docente.csv' WITH DELIMITER ',' CSV HEADER ENCODING 'UTF-8';

In [22]:
#Vamos a crear la df relacionada a Vertical
vertical = pd.DataFrame()
vertical["Vertical_id"] = df["Vertical_id"]
vertical["Campus"] = Campus
vertical["Promocion"] = Promocion
vertical = vertical.head(4)

In [23]:
#Para esta dataframe, cambiamos valores a mano para adecuarla.
vertical.at[1, 'Vertical_id'] = 'DS_FEB'
vertical.at[3, 'Vertical_id'] = 'FS_FEB'
vertical.at[1, 'Promocion'] = 'Febrero'
vertical.at[3, 'Promocion'] = 'Febrero'

In [24]:
#Creamos la columna de fechas y la metemos.
#vamos a cojer de las DF de alumnos las fechas de febrero y septiembre
Fecha_febrero = df_fs2.at[1,"Fecha_comienzo"]
Fecha_septiembre = df_ds1.at[1,"Fecha_comienzo"]
#aqui ya metemos las fechas en su lugar correspondiente.
vertical["Fecha_comienzo"] = vertical["Promocion"]
vertical.loc[vertical['Promocion'] == 'Septiembre', 'Fecha_comienzo'] = Fecha_septiembre
vertical.loc[vertical['Promocion'] == 'Febrero', 'Fecha_comienzo'] = Fecha_febrero
vertical

  Vertical_id    Campus   Promocion Fecha_comienzo
0      DS_SEP    Madrid  Septiembre     18/09/2023
1      DS_FEB    Madrid     Febrero     12/02/2024
2      FS_SEP    Madrid  Septiembre     18/09/2023
3      FS_FEB  Valencia     Febrero     12/02/2024

In [25]:
#El formato de fecha de SQL es YYYY-MM-DD
#vamos a cambiarle, el tipo de columna a tipo datetime
vertical['Fecha_comienzo'] = pd.to_datetime(vertical['Fecha_comienzo'], format='%d/%m/%Y')

#ahora, cambiamos el formato de la fecha

vertical['Fecha_comienzo'] = vertical['Fecha_comienzo'].dt.strftime('%Y-%m-%d')
vertical

  Vertical_id    Campus   Promocion Fecha_comienzo
0      DS_SEP    Madrid  Septiembre     2023-09-18
1      DS_FEB    Madrid     Febrero     2024-02-12
2      FS_SEP    Madrid  Septiembre     2023-09-18
3      FS_FEB  Valencia     Febrero     2024-02-12

In [26]:
#Tabla terminada, la guardamos.
ruta = 'data_limpiado/Vertical.csv'
vertical.to_csv(ruta, index=False)

In [27]:
#Creamos la tabla estudiantes.

estudiantes_DS = pd.DataFrame()
estudiantes_FS = pd.DataFrame()
#Solo nos interesan columnas en particular, juntamos todas las filas de las 4 tablas por las columnas que queremos.


estudiantes_DS["Email"] = pd.concat([df_ds1["Email"], df_ds2["Email"]], axis=0, ignore_index=True)
estudiantes_DS["Vertical_id"] = pd.concat([df_ds1["Campus"], df_ds2["Campus"]], axis=0, ignore_index=True)

estudiantes_FS["Email"] = pd.concat([df_fs1["Email"], df_fs2["Email"]], axis=0, ignore_index=True)
estudiantes_FS["Vertical_id"] = pd.concat([df_fs1["Campus"], df_fs2["Campus"]], axis=0, ignore_index=True)

#Vamos a cambiar la vertical_id segun la fecha de comienzo, metemos la fecha de comienzo de cada estudiante.
estudiantes_DS["Fecha_comienzo"] = pd.concat([df_ds1["Fecha_comienzo"], df_ds2["Fecha_comienzo"]], axis=0, ignore_index=True)
estudiantes_FS["Fecha_comienzo"] = pd.concat([df_fs1["Fecha_comienzo"], df_fs2["Fecha_comienzo"]], axis=0, ignore_index=True)

In [28]:
#Aqui, cambiamos, segun sean de Madrid o valencia, y segun su fecha de comienzo
estudiantes_DS.loc[(estudiantes_DS["Fecha_comienzo"] == Fecha_febrero), 'Vertical_id'] = 'DS_FEB'
estudiantes_DS.loc[(estudiantes_DS["Fecha_comienzo"] == Fecha_septiembre), 'Vertical_id'] = 'DS_SEP'
estudiantes_FS.loc[(estudiantes_FS["Fecha_comienzo"] == Fecha_febrero), 'Vertical_id'] = 'FS_FEB'
estudiantes_FS.loc[(estudiantes_FS["Fecha_comienzo"] == Fecha_septiembre), 'Vertical_id'] = 'FS_SEP'

In [29]:
#Ultimos ajustes para adaptarla a nuestro esquema.
estudiantes_final = pd.concat([estudiantes_DS, estudiantes_FS], axis=0, ignore_index=True)
estudiantes_final = estudiantes_final.drop("Fecha_comienzo", axis=1)
estudiantes_final["Nombre"] = pd.concat([df_ds1["Nombre"], df_ds2["Nombre"],df_fs1["Nombre"], df_fs2["Nombre"]], axis=0, ignore_index=True)
estudiantes_final

                             Email Vertical_id                Nombre
0           Jafet_Casals@gmail.com      DS_SEP          Jafet Casals
1       Jorge_Manzanares@gmail.com      DS_SEP      Jorge Manzanares
2          Onofre_Adadia@gmail.com      DS_SEP         Onofre Adadia
3           Merche_Prada@gmail.com      DS_SEP          Merche Prada
4           Pilar_Abella@gmail.com      DS_SEP          Pilar Abella
5           Leoncio_Tena@gmail.com      DS_SEP          Leoncio Tena
6        Odalys_Torrijos@gmail.com      DS_SEP       Odalys Torrijos
7       Eduardo_Caparrós@gmail.com      DS_SEP      Eduardo Caparrós
8     Ignacio_Goicoechea@gmail.com      DS_SEP    Ignacio Goicoechea
9      Clementina_Santos@gmail.com      DS_SEP     Clementina Santos
10         Daniela_Falcó@gmail.com      DS_SEP         Daniela Falcó
11         Abraham_Vélez@gmail.com      DS_SEP         Abraham Vélez
12  Maximiliano_Menéndez@gmail.com      DS_SEP  Maximiliano Menéndez
13         Anita_Heredia@gmail.com      DS_SEP         Anita Heredia
14             Eli_Casas@gmail.com      DS_SEP             Eli Casas
15     Guillermo_Borrego@gmail.com      DS_FEB     Guillermo Borrego
16        Sergio_Aguirre@gmail.com      DS_FEB        Sergio Aguirre
17       Carlito_Carrión@gmail.com      DS_FEB       Carlito Carrión
18       Haydée_Figueroa@gmail.com      DS_FEB       Haydée Figueroa
19         Chita_Mancebo@gmail.com      DS_FEB         Chita Mancebo
20      Joaquina_Asensio@gmail.com      DS_FEB      Joaquina Asensio
21      Cristian_Sarabia@gmail.com      DS_FEB      Cristian Sarabia
22         Isabel_Ibáñez@gmail.com      DS_FEB         Isabel Ibáñez
23       Desiderio_Jordá@gmail.com      DS_FEB       Desiderio Jordá
24       Rosalina_Llanos@gmail.com      DS_FEB       Rosalina Llanos
25        Amor_Larrañaga@gmail.com      FS_SEP        Amor Larrañaga
26      Teodoro_Alberola@gmail.com      FS_SEP      Teodoro Alberola
27           Cleto_Plana@gmail.com      FS_SEP           Cleto Plana
28      Aitana_Sebastián@gmail.com      FS_SEP      Aitana Sebastián
29      Dolores_Valbuena@gmail.com      FS_SEP      Dolores Valbuena
30          Julie_Ferrer@gmail.com      FS_SEP          Julie Ferrer
31        Mireia_Cabañas@gmail.com      FS_SEP        Mireia Cabañas
32         Flavia_Amador@gmail.com      FS_SEP         Flavia Amador
33         Albino_Macias@gmail.com      FS_SEP         Albino Macias
34         Ester_Sánchez@gmail.com      FS_SEP         Ester Sánchez
35    Luis_Miguel_Galvez@gmail.com      FS_SEP    Luis Miguel Galvez
36        Loida_Arellano@gmail.com      FS_SEP        Loida Arellano
37        Heraclio_Duque@gmail.com      FS_SEP        Heraclio Duque
38     Herberto_Figueras@gmail.com      FS_SEP     Herberto Figueras
39         Teresa_Laguna@gmail.com      FS_FEB         Teresa Laguna
40      Estrella_Murillo@gmail.com      FS_FEB      Estrella Murillo
41       Ernesto_Uriarte@gmail.com      FS_FEB       Ernesto Uriarte
42       Daniela_Guitart@gmail.com      FS_FEB       Daniela Guitart
43        Timoteo_Trillo@gmail.com      FS_FEB        Timoteo Trillo
44         Ricarda_Tovar@gmail.com      FS_FEB         Ricarda Tovar
45   Alejandra_Vilaplana@gmail.com      FS_FEB   Alejandra Vilaplana
46       Daniel_Rosselló@gmail.com      FS_FEB       Daniel Rosselló
47         Rita_Olivares@gmail.com      FS_FEB         Rita Olivares
48          Cleto_Montes@gmail.com      FS_FEB          Cleto Montes
49       Marino_Castilla@gmail.com      FS_FEB       Marino Castilla
50   Estefanía_Valcárcel@gmail.com      FS_FEB   Estefanía Valcárcel
51        Noemí_Vilanova@gmail.com      FS_FEB        Noemí Vilanova

In [30]:
#ya esta terminada, la importamos.
ruta = 'data_limpiado/Estudiantes.csv'
estudiantes_final.to_csv(ruta, index=False)

In [31]:
#Creamos la tablas proyectos segun vertical, para registrar las calificaciones de cada alumno.
proyectos_DS = pd.DataFrame()


# Añadimos las columnas de los emails correspondientes que van a ser las primary keys en cada tabla correspondiente por vertical
proyectos_DS['Email'] = estudiantes_DS["Email"]

# Añadimos todas las columnas de los diferentes proyectos y sus califaciones correspondientes
proyectos_DS["Proyecto_HLF"] = pd.concat([df_ds1["Proyecto_HLF"], df_ds2["Proyecto_HLF"]], axis=0, ignore_index=True)
proyectos_DS["Proyecto_EDA"] = pd.concat([df_ds1["Proyecto_EDA"], df_ds2["Proyecto_EDA"]], axis=0, ignore_index=True)
proyectos_DS["Proyecto_BBDD"] = pd.concat([df_ds1["Proyecto_BBDD"], df_ds2["Proyecto_BBDD"]], axis=0, ignore_index=True)
proyectos_DS["Proyecto_ML"] = pd.concat([df_ds1["Proyecto_ML"], df_ds2["Proyecto_ML"]], axis=0, ignore_index=True)
proyectos_DS["Proyecto_Deployment"] = pd.concat([df_ds1["Proyecto_Deployment"], df_ds2["Proyecto_Deployment"]], axis=0, ignore_index=True)

proyectos_DS

,Email,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment
0,Jafet_Casals@gmail.com,Apto,No Apto,Apto,Apto,Apto
1,Jorge_Manzanares@gmail.com,Apto,No Apto,Apto,Apto,Apto
2,Onofre_Adadia@gmail.com,Apto,Apto,Apto,No Apto,Apto
3,Merche_Prada@gmail.com,Apto,No Apto,No Apto,Apto,No Apto
4,Pilar_Abella@gmail.com,Apto,No Apto,Apto,Apto,Apto
5,Leoncio_Tena@gmail.com,Apto,Apto,Apto,Apto,Apto
6,Odalys_Torrijos@gmail.com,No Apto,Apto,Apto,Apto,Apto
7,Eduardo_Caparrós@gmail.com,No Apto,Apto,Apto,Apto,Apto
8,Ignacio_Goicoechea@gmail.com,Apto,Apto,Apto,No Apto,Apto
9,Clementina_Santos@gmail.com,Apto,No Apto,Apto,Apto,Apto
10,Daniela_Falcó@gmail.com,Apto,Apto,Apto,Apto,Apto
11,Abraham_Vélez@gmail.com,Apto,No Apto,No Apto,Apto,Apto
12,Maximiliano_Menéndez@gmail.com,Apto,No Apto,Apto,Apto,Apto
13,Anita_Heredia@gmail.com,Apto,Apto,Apto,Apto,Apto
14,Eli_Casas@gmail.com,Apto,Apto,Apto,Apto,Apto
15,Guillermo_Borrego@gmail.com,Apto,No Apto,No Apto,Apto,No Apto
16,Sergio_Aguirre@gmail.com,Apto,No Apto,Apto,Apto,No Apto
17,Carlito_Carrión@gmail.com,Apto,No Apto,Apto,Apto,Apto
18,Haydée_Figueroa@gmail.com,Apto,Apto,Apto,Apto,Apto
19,Chita_Mancebo@gmail.com,No Apto,Apto,No Apto,Apto,Apto
20,Joaquina_Asensio@gmail.com,No Apto,No Apto,Apto,Apto,Apto
21,Cristian_Sarabia@gmail.com,Apto,Apto,No Apto,Apto,Apto
22,Isabel_Ibáñez@gmail.com,No Apto,Apto,No Apto,Apto,Apto
23,Desiderio_Jordá@gmail.com,No Apto,Apto,No Apto,No Apto,Apto
24,Rosalina_Llanos@gmail.com,Apto,Apto,Apto,Apto,Apto

In [32]:
#ya esta terminada, la importamos.
ruta = 'data_limpiado/proyectos_DS.csv'
proyectos_DS.to_csv(ruta, index=False)

In [33]:
#Creamos la tablas proyectos segun vertical, para registrar las calificaciones de cada alumno.

proyectos_FS = pd.DataFrame()


# Añadimos las columnas de los emails correspondientes que van a ser las primary keys en cada tabla correspondiente por vertical

proyectos_FS['Email'] = estudiantes_FS["Email"]

# Añadimos todas las columnas de los diferentes proyectos y sus califaciones correspondientes
proyectos_FS["Proyecto_WebDev"] = pd.concat([df_fs1["Proyecto_WebDev"], df_fs2["Proyecto_WebDev"]], axis=0, ignore_index=True)
proyectos_FS["Proyecto_FrontEnd"] = pd.concat([df_fs1["Proyecto_FrontEnd"], df_fs2["Proyecto_FrontEnd"]], axis=0, ignore_index=True)
proyectos_FS["Proyecto_BackEnd"] = pd.concat([df_fs1["Proyecto_Backend"], df_fs2["Proyecto_Backend"]], axis=0, ignore_index=True)
proyectos_FS["Proyecto_React"] = pd.concat([df_fs1["Proyecto_React"], df_fs2["Proyecto_React"]], axis=0, ignore_index=True)
proyectos_FS["Proyecto_FullStack"] = pd.concat([df_fs1["Proyecto_FullStack"], df_fs2["Proyecto_FullStack"]], axis=0, ignore_index=True)

proyectos_FS

,Email,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_BackEnd,Proyecto_React,Proyecto_FullStack
0,Amor_Larrañaga@gmail.com,Apto,Apto,Apto,Apto,No Apto
1,Teodoro_Alberola@gmail.com,No Apto,No Apto,Apto,No Apto,Apto
2,Cleto_Plana@gmail.com,Apto,No Apto,Apto,No Apto,Apto
3,Aitana_Sebastián@gmail.com,Apto,No Apto,Apto,No Apto,Apto
4,Dolores_Valbuena@gmail.com,Apto,Apto,Apto,Apto,No Apto
5,Julie_Ferrer@gmail.com,No Apto,No Apto,No Apto,Apto,No Apto
6,Mireia_Cabañas@gmail.com,No Apto,Apto,Apto,Apto,Apto
7,Flavia_Amador@gmail.com,Apto,Apto,No Apto,Apto,Apto
8,Albino_Macias@gmail.com,No Apto,Apto,Apto,Apto,Apto
9,Ester_Sánchez@gmail.com,No Apto,Apto,Apto,No Apto,Apto
10,Luis_Miguel_Galvez@gmail.com,No Apto,Apto,Apto,Apto,Apto
11,Loida_Arellano@gmail.com,Apto,Apto,Apto,Apto,Apto
12,Heraclio_Duque@gmail.com,Apto,Apto,No Apto,No Apto,No Apto
13,Herberto_Figueras@gmail.com,Apto,Apto,Apto,Apto,Apto
14,Teresa_Laguna@gmail.com,Apto,Apto,Apto,Apto,Apto
15,Estrella_Murillo@gmail.com,Apto,Apto,No Apto,Apto,Apto
16,Ernesto_Uriarte@gmail.com,Apto,Apto,Apto,Apto,Apto
17,Daniela_Guitart@gmail.com,Apto,No Apto,No Apto,Apto,Apto
18,Timoteo_Trillo@gmail.com,No Apto,Apto,Apto,Apto,No Apto
19,Ricarda_Tovar@gmail.com,Apto,Apto,Apto,Apto,Apto
20,Alejandra_Vilaplana@gmail.com,No Apto,No Apto,No Apto,Apto,Apto
21,Daniel_Rosselló@gmail.com,No Apto,No Apto,Apto,No Apto,No Apto
22,Rita_Olivares@gmail.com,No Apto,No Apto,No Apto,Apto,Apto
23,Cleto_Montes@gmail.com,Apto,Apto,No Apto,Apto,Apto
24,Marino_Castilla@gmail.com,No Apto,No Apto,Apto,No Apto,No Apto
25,Estefanía_Valcárcel@gmail.com,Apto,Apto,No Apto,No Apto,Apto
26,Noemí_Vilanova@gmail.com,Apto,No Apto,No Apto,Apto,Apto

In [34]:
#ya esta terminada, la importamos.
ruta = 'data_limpiado/proyectos_FS.csv'
proyectos_FS.to_csv(ruta, index=False)

ORDEN CREACION DE TABLAS:

CREAR TABLA VERTICAL

CREATE TABLE vertical (
    Vertical_id TEXT PRIMARY KEY,
    Campus TEXT,
    Promocion TEXT,
    Fecha_comienzo DATE
);

importar CSV:

\copy vertical from 'C:\Users\Usuario\Desktop\2309_sql_thebridge\Practica\4-Proyecto\data_limpiado\Vertical.csv' WITH DELIMITER ',' CSV HEADER ENCODING 'UTF-8';

CREAR TABLA ESTUDIANTES

CREATE TABLE Estudiantes (
    Email TEXT PRIMARY KEY,
    Vertical_id TEXT,
    Nombre TEXT,
    FOREIGN KEY (Vertical_ID) REFERENCES vertical(Vertical_id)
);

importar CSV:

\copy estudiantes from 'C:\Users\Usuario\Desktop\2309_sql_thebridge\Practica\4-Proyecto\data_limpiado\Estudiantes.csv' WITH DELIMITER ',' CSV HEADER ENCODING 'UTF-8';

CREAR TABLA CUERPO DOCENTE

CREATE TABLE cuerpo_docente (
    Docente_id SERIAL PRIMARY KEY,
    nombre TEXT,
    rol TEXT,
    vertical_ID TEXT,
    FOREIGN KEY (vertical_ID) REFERENCES vertical(Vertical_id)
);

importar CSV:

\copy cuerpo_docente from 'C:\Users\Usuario\Desktop\2309_sql_thebridge\Practica\4-Proyecto\data_limpiado\cuerpo_docente.csv' WITH DELIMITER ',' CSV HEADER ENCODING 'UTF-8';

CREAR TABLA PROYECTOS_DS

CREATE TABLE proyectos_DS (
    Email TEXT PRIMARY KEY,
    Proyecto_HLF TEXT,
    Proyecto_EDA TEXT,
    Proyecto_BBDD TEXT,
    Proyecto_ML TEXT,
    Proyecto_Deployment TEXT
);

importar CSV:

\copy proyectos_DS from 'C:\Users\Usuario\Desktop\2309_sql_thebridge\Practica\4-Proyecto\data_limpiado\proyectos_DS.csv' WITH DELIMITER ',' CSV HEADER ENCODING 'UTF-8';

CREAR TABLA PROYECTOS_FS

CREATE TABLE proyectos_FS (
    Email TEXT PRIMARY KEY ,
    Proyecto_WebDev TEXT,
    Proyecto_FrontEnd TEXT,
    Proyecto_BackEnd TEXT,
    Proyecto_React TEXT,
    Proyecto_FullStack TEXT
);

importar CSV:

\copy proyectos_FS from 'C:\Users\Usuario\Desktop\2309_sql_thebridge\Practica\4-Proyecto\data_limpiado\proyectos_FS.csv' WITH DELIMITER ',' CSV HEADER ENCODING 'UTF-8';